spring:
  profiles.active: local

---

spring:
  profiles: default

multipart:
  maxFileSize: 5000KB
  maxRequestSize: 5000KB

security:
  user.password: pass

razorpay:
  key-id: rzp_test_aoq1vFZS49sAlN
  key-secret: y1hIwOiePI3N3Ruaj7dsu53z

---

spring:
  profiles: unit-test
  jpa:
    generate-ddl: false
    hibernate.ddl-auto:
  datasource:
    initialize: true
    data: none
  h2.console.enabled: true

logging.level.org.hibernate.SQL: DEBUG

---

spring:
  profiles: local
  jpa:
    generate-ddl: false
    hibernate.ddl-auto:
  datasource:
    initialize: true
  h2.console.enabled: true

logging.level.org.hibernate.SQL: DEBUG

---

spring:
  profiles: dev
  jpa:
    generate-ddl: false
    hibernate.ddl-auto:
  datasource:
    initialize: false
    url: jdbc:mysql://l3855uft9zao23e2.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/avh2fhkb22dm0j8k
    username: z9td61e4pbq5xu01
    password: t4kmyhxgoblzgyeb
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 8
    initial-size: 5
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1

logging.level.org.hibernate.SQL: DEBUG

---

spring:
  profiles: uat
  jpa:
      generate-ddl: false
      hibernate.ddl-auto:
  datasource:
      initialize: false
      url: jdbc:mysql://l3855uft9zao23e2.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/avh2fhkb22dm0j8k
      username: z9td61e4pbq5xu01
      password: t4kmyhxgoblzgyeb
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 8
      initial-size: 5
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1

logging.level.org.hibernate.SQL: DEBUG


