spring:
  profiles.active: unit-test
---
spring:
  profiles: default
---
spring:
  profiles: unit-test
  h2.console.enabled: true
  jpa.hibernate.ddl-auto: none

logging.level.org.hibernate.SQL: DEBUG