spring:
  profiles.active: dev

---

spring:
  profiles: default

multipart:
  maxFileSize: 5000KB
  maxRequestSize: 5000KB

razorpay:
  key-id: rzp_test_aoq1vFZS49sAlN
  key-secret: y1hIwOiePI3N3Ruaj7dsu53z

---

spring:
  profiles: unit-test
  jpa.generate-ddl: true
  h2.console.enabled: true
  jpa.hibernate.ddl-auto: create

logging.level.org.hibernate.SQL: DEBUG

---

spring:
  profiles: dev
  jpa.generate-ddl: false
  jpa.hibernate.ddl-auto:
  datasource.initialize: false
  datasource.url: jdbc:mysql://l3855uft9zao23e2.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/avh2fhkb22dm0j8k
  datasource.username: z9td61e4pbq5xu01
  datasource.password: t4kmyhxgoblzgyeb
  datasource.driver-class-name: com.mysql.jdbc.Driver

logging.level.org.hibernate.SQL: DEBUG

---

spring:
  profiles: uat
  jpa.generate-ddl: false
  jpa.hibernate.ddl-auto:
  datasource.initialize: false
  datasource.url: jdbc:mysql://l3855uft9zao23e2.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/avh2fhkb22dm0j8k
  datasource.username: z9td61e4pbq5xu01
  datasource.password: t4kmyhxgoblzgyeb
  datasource.driver-class-name: com.mysql.jdbc.Driver

logging.level.org.hibernate.SQL: DEBUG




