create schema if not exists ROAMY;

drop table ROAMY.city if exists;
drop table ROAMY.category if exists;
drop table ROAMY.user if exists;
drop table ROAMY.trip if exists;
drop table ROAMY.trip_category if exists;
drop table ROAMY.trip_city if exists;
drop table ROAMY.trip_instance if exists;
drop table ROAMY.vendor if exists;
drop table ROAMY.vendor_city if exists;
drop table ROAMY.vendor_account if exists;
drop table ROAMY.payment if exists;
drop table ROAMY.reservation if exists;

create table ROAMY.city (
    id bigint generated by default as identity,
    name varchar(64) not null,
    status varchar(64) not null,
    created_by varchar(256) not null,
    created_on timestamp not null,
    last_modified_by varchar(256) not null,
    last_modified_on timestamp not null,
    primary key (id)
);

create table ROAMY.category (
    id bigint generated by default as identity,
    name varchar(64) not null,
    description varchar(256),
    status varchar(64) not null,
    created_by varchar(256) not null,
    created_on timestamp not null,
    last_modified_by varchar(256) not null,
    last_modified_on timestamp not null,
    primary key (id)
);

create table ROAMY.user (
    id bigint generated by default as identity,
    type varchar(64) not null,
    email varchar(64) not null,
    pass varchar(64),
    fname varchar(64),
    lname varchar(64),
    birth_date timestamp,
    address varchar(64),
    city varchar(64),
    country varchar(64),
    pin varchar(64),
    phone_number varchar(64),
    status varchar(64) not null,
    v_code varchar(64),
    v_expiry timestamp,
    verified boolean,
    created_by varchar(256) not null,
    created_on timestamp not null,
    last_modified_by varchar(256) not null,
    last_modified_on timestamp not null,
    primary key (id)
);

create table ROAMY.trip (
    id bigint generated by default as identity,
    name varchar(256) not null,
    code varchar(256) not null,
    description varchar(1024),
    difficulty_level integer,
    number_of_days integer,
    price_per_adult double,
    tac double,
    itinerary varchar(1024),
    inclusions varchar(1024),
    exclusions varchar(1024),
    meeting_points varchar(1024),
    status varchar(64) not null,
    created_by varchar(256) not null,
    created_on timestamp not null,
    last_modified_by varchar(256) not null,
    last_modified_on timestamp not null,
    primary key (id)
);

create table ROAMY.trip_category (
    trip_id bigint not null,
    category_id bigint not null
);

alter table ROAMY.trip_category add constraint FK_ql0wkpoc62tm3u56lgymaa372 foreign key (category_id) references ROAMY.category;
alter table ROAMY.trip_category add constraint FK_avrcvkgq63ii09pqvtmwfy1we foreign key (trip_id) references ROAMY.trip;

create table ROAMY.trip_city (
    trip_id bigint not null,
    city_id bigint not null
);

alter table ROAMY.trip_city add constraint FK_d15hc5jcot3vacepxfy59ijf9 foreign key (city_id) references ROAMY.city;
alter table ROAMY.trip_city add constraint FK_3rm0e5kwpiqtqgpltclc5fvss foreign key (trip_id) references ROAMY.trip;

create table ROAMY.trip_instance (
    id bigint generated by default as identity,
    traveller_capacity integer not null,
    additional_capacity integer,
    date timestamp not null,
    display_start_date timestamp,
    display_end_date timestamp,
    status varchar(64) not null,
    created_by varchar(256) not null,
    created_on timestamp not null,
    last_modified_by varchar(256) not null,
    last_modified_on timestamp not null,
    primary key (id)
);

create table ROAMY.vendor (
    id bigint generated by default as identity,
    name varchar(256) not null,
    phone_number varchar(64),
    email varchar(256),
    additional_email varchar(256),
    notes varchar(2048),
    status varchar(64) not null,
    created_by varchar(256) not null,
    created_on timestamp not null,
    last_modified_by varchar(256) not null,
    last_modified_on timestamp not null,
    primary key (id)
);

create table ROAMY.vendor_account (
    id bigint generated by default as identity,
    name varchar(256) not null,
    vendor_id bigint,
    bank_name varchar(256) not null,
    account_number varchar(64) not null,
    ifsc_code varchar(64) not null,
    pan varchar(64),
    tan varchar(64),
    service_tax_number varchar(64),
    status varchar(64) not null,
    created_by varchar(256) not null,
    created_on timestamp not null,
    last_modified_by varchar(256) not null,
    last_modified_on timestamp not null,
    primary key (id)
);

alter table ROAMY.vendor_account add constraint FK_3rqb02v5mye4g355doykob2jy foreign key (vendor_id) references ROAMY.vendor;

create table ROAMY.vendor_city (
    vendor_id bigint not null,
    city_id bigint not null
);

alter table ROAMY.vendor_city add constraint FK_4j8swfvu7rh4jut26y5j39eku foreign key (city_id) references ROAMY.city;
alter table ROAMY.vendor_city add constraint FK_oxmyss8pw69n7hwg2aaoc5wrg foreign key (vendor_id) references ROAMY.vendor;

create table ROAMY.payment (
    id bigint generated by default as identity,
    amount double not null,
    date timestamp not null,
    status varchar(64) not null,
    created_by varchar(256) not null,
    created_on timestamp not null,
    last_modified_by varchar(256) not null,
    last_modified_on timestamp not null,
    primary key (id)
);

create table ROAMY.reservation (
    id bigint generated by default as identity,
    email varchar(256) not null,
    number_of_travellers integer not null,
    phone_number varchar(64) not null,
    status varchar(64) not null,
    created_by varchar(256) not null,
    created_on timestamp not null,
    last_modified_by varchar(256) not null,
    last_modified_on timestamp not null,
    primary key (id)
);
